-- SQL query generated for Table :INT_FCT_POS_TXN_DLY

SELECT F_F_POS_TXN_DR_CR_IND, V_F_POS_TXN_TYPE, V_F_POS_TXN_SRC_CUSTOMER_REF_CODE, V_F_POS_TXN_RESPONDER_CODE, V_F_POS_TXN_RESP_CODE, V_F_POS_SRC_TRANSACT_CTRY, V_F_POS_CARD_FIID, V_F_POS_TERM_FIID, BUSINES_DT FROM INT_FCT_POS_TXN_DLY ;


-- SQL query generated for Table :ODS_VP_PTH2

SELECT V_F_CDM_REF_NBR, PTH2_346_OCCUPATION_TYPE, PTH2_347_SALARIED_EMPL_TYPE, PTH2_348_SELF_EMP_TYPE, PTH2_146_POSTAL_CODE, PTH2_074_OFFICE_PIN_CODE FROM ODS_VP_PTH2 ;


-- SQL query generated for Table :FCT_DB_SCRIPT_HOLDING_REP

SELECT V_F_DB_SCRIP_ISIN, N_F_DB_SCRIP_NO_OF_SHARES, N_F_DB_SCRIP_VALUE, V_F_DB_SCRIP_COMB_ACCT_NBR, BUSINESS_DT FROM FCT_DB_SCRIPT_HOLDING_REP ;


-- SQL query generated for Table :INT_FN_CUSTOMER

SELECT D_F_FN_CUSTOMER_CLOSED_DATE, V_F_FN_CUSTOMER_OFF_PIN, V_F_FN_CUSTOMER_RESI_PIN_CODE, V_F_FN_FW_CUSTOMER_REF_CODE, BUSINESS_DT FROM INT_FN_CUSTOMER ;


-- SQL query generated for Table :INT_FN_COLLATERAL

SELECT V_F_FN_COLL_ACCOUNT_NBR, V_F_FN_COLL_MODEL, BUSINESS_DT FROM INT_FN_COLLATERAL ;


-- SQL query generated for Table :INT_FCT_VP_ATH2

SELECT N_ATH2_MT_POSTING_FLAG, F_ATH2_RECORD_STATUS, V_ATH2_MERCH_CNTRY_CODE, D_MISDATE, V_ATH2_CDM_REF_NBR, V_ATH2_FIC_CUST_REF_CODE, FIC_MIS_DATE, V_ATH2_ACCT, F_ATH2_MT_TYPE, N_ATH2_MT_TXN_CODE, D_ATH2_MT_AMOUNT, D_ATH2_MT_POSTING_DATE, V_ATH2_MT_REF_NBR, N_ATH2_MT_CATEGORY_CODE FROM INT_FCT_VP_ATH2 ;


-- SQL query generated for Table :INT_FCT_VP_COC_EMI

SELECT D_MIS_DATE, V_F_COC_EMI_FIC_CUST_REF_CODE, V_F_COC_EMI_CDM_REF_NBR, V_F_COC_EMI_PD_CODE, N_F_COC_EMI_LOGO, V_F_COC_EMI_CARD_NBR, V_F_COC_EMI_CHG_TYPE, N_F_COC_EMI_LOANAMOUNT, D_F_COC_EMI_DATE_LOAN_BOOKED, F_F_COC_EMI_STATUS FROM INT_FCT_VP_COC_EMI ;


-- SQL query generated for Table :FCT_ALL_ACCOUNTS_SUMMARY

SELECT V_F_ACCT_PROD_BUSS_SEG_CODE, V_F_ACCT_PROD_CODE, V_F_ACCT_SOURCE_SYSTEM, V_F_ACCT_SRC_CUSTOMER_REF_CODE, BUSINESS_DT, N_F_ACCT_EOP_BAL, N_F_ACCT_ORIGINAL_BALANCE, N_F_ACCT_TOT_FEE_CHGS, V_F_ACCT_ACCT_NUMBER, V_F_ACCT_FIC_CUSTOMER_REF_CODE, N_F_ACCT_AVG_BALANCE, N_F_ACCT_CASA_AQB_QTD, D_F_ACCT_ACTIVATION_DATE, D_F_ACCT_CLOSED_DATE, D_F_ACCT_CUSTOMER_ESTB_DATE, D_F_ACCT_DATE_LAST_TXN_ATM, D_F_ACCT_DATE_LAST_TXN_BRN, D_F_ACCT_DATE_LAST_TXN_IVR, D_F_ACCT_DATE_LAST_TXN_MOB, D_F_ACCT_DATE_LAST_TXN_NET, D_F_ACCT_DATE_LAST_TXN_POS, D_F_ACCT_LAST_ACTIVITY_DATE, D_F_ACCT_MATURITY_DATE, D_F_ACCT_NET_CHN_REG_DATE, D_F_ACCT_START_DATE, F_F_ACCT_CLOSED_IND, F_F_ACCT_CUSTOMER_CLOSED_IND, F_F_ACCT_DORM_CODE, F_F_ACCT_EMPLOYEE_IND, F_F_ACCT_PROD_FMLY FROM FCT_ALL_ACCOUNTS_SUMMARY ;


-- SQL query generated for Table :DIM_CUSTOMER

SELECT V_D_CUSTOMER_FULL_NAME, V_D_CUSTOMER_GENDER, V_D_CUSTOMER_IT_NBR, V_D_CUSTOMER_LAST_NAME, V_D_CUSTOMER_MARITAL_STATUS, V_D_CUSTOMER_MOBILE_PHONE, V_D_CUSTOMER_OFF_PHONE, V_D_CUSTOMER_OFF_ZIP_CODE, V_D_CUSTOMER_PROFESSION, V_D_CUSTOMER_RESI_PHONE, V_D_CUSTOMER_SEGMENT, V_D_CUSTOMER_ZIP_CODE, V_D_FIC_CUSTOMER_REF_CODE, D_D_CUSTOMER_CLOSED_DATE, D_D_CUSTOMER_DATE_OF_BIRTH, D_D_CUSTOMER_REC_END_DATE, F_D_CUSTOMER_LEGAL_ENTITY, F_D_CUSTOMER_REC_CURR_FLG, F_D_CUSTOMER_STAFF_IND, N_D_CUSTOMER_DEPENDENTS, V_D_CUSTOMER_BRANCH_CODE, V_D_CUSTOMER_CITY, V_D_CUSTOMER_EDUCATION, V_D_CUSTOMER_EMAIL_ADD, V_D_CUSTOMER_FIRST_NAME FROM DIM_CUSTOMER ;


-- SQL query generated for Table :FCT_POS_TXN

SELECT F_F_POS_TXN_DRCR_IND, F_F_POS_TXN_STATUS, N_F_POS_TXN_AMOUNT, V_F_POS_FIC_CUSTOMER_REF_CODE, D_F_POS_TRANS_DATE, V_F_POS_TXN_CODE, V_F_POS_SRC_CUSTOMER_REF_CODE, V_F_POS_TXN_RETAILER_BUSS, BUSINESS_DT FROM FCT_POS_TXN ;


-- SQL query generated for Table :FCT_IB_REGISTRATION

SELECT V_F_IB_REG_SRC_CUSTOMER_REF_CODE, D_F_IB_REG_REG_DATE, D_F_IB_REG_DEREG_DATE, BUSINESS_DT FROM FCT_IB_REGISTRATION ;


-- SQL query generated for Table :FCT_DB_TXN_REP

SELECT N_F_DB_TXN_VALUE, V_F_DB_TXN_COMB_ACCT_NBR, BUSINESS_DT, F_F_DB_TXN_DR_CR_CODE FROM FCT_DB_TXN_REP ;


-- SQL query generated for Table :INT_FCT_VP_ATH3

SELECT N_ATH3_FH_ANT_PMTS6, V_ATH3_FIC_CUST_REF_CODE, V_ATH3_FINAL_BLOCK_CODE, MIS_DATE, N_ATH3_FH_ANT_PMTS1, N_ATH3_FH_END_STMT_BAL2, N_ATH3_FH_ANT_PMTS2, N_ATH3_FH_END_STMT_BAL3, N_ATH3_FH_ANT_PMTS3, N_ATH3_FH_END_STMT_BAL4, N_ATH3_FH_ANT_PMTS4, N_ATH3_FH_END_STMT_BAL5, N_ATH3_FH_ANT_PMTS5, N_ATH3_FH_END_STMT_BAL6, N_ATH3_FH_END_STMT_BAL1, D_ATH3_GRTST_CARD_EXPR_DATE, D_MISDATE, V_ATH3_LOGO, V_ATH3_ACCT, N_ATH3_CRLIM, V_ATH3_USER_ACCT_NBR FROM INT_FCT_VP_ATH3 ;


-- SQL query generated for Table :INT_TPP_CONSOLIDATED

SELECT V_F_FIC_PROD_CODE, V_F_FINWARE_CUSTOMER_ID, V_F_FUND_TYPE, V_F_PRODUCT_NAME, BUSINESS_DT, MIS_DATE, N_F_AMOUNT FROM INT_TPP_CONSOLIDATED ;


-- SQL query generated for Table :INT_BILL_PAY_REG_DTLS

SELECT BUSINESS_DT, V_F_BP_CUSTOMERID FROM INT_BILL_PAY_REG_DTLS ;


-- SQL query generated for Table :FCT_ATMPOS_REGISTRATION

SELECT V_F_ATMPOS_REG_SRC_CUSTOMER_REF_CODE, V_F_ATMPOS_REG_CARD_NO, D_F_ATMPOS_REG_MIS_DATE, D_F_ATMPOS_REG_REG_DATE, F_F_ATMPOS_CARD_HOTLIST_FLG, D_F_ATMPOS_DEREG_DATE, D_F_ATMPOS_TXN_CARD_EXPIRY_DATE, V_F_ATMPOS_TXN_PRIM_ACCT_NBR, F_F_CURR_REC_FLG FROM FCT_ATMPOS_REGISTRATION ;


-- SQL query generated for Table :INT_CASA_ACCOUNTS

SELECT N_F_CASA_AVERAGE_BALANCE_CR, V_CASA_BRANCH_CODE, V_F_CASA_ACCT_NO, V_F_CASA_CUSTOMER_REF_CODE, BUSINESS_DT FROM INT_CASA_ACCOUNTS ;


-- SQL query generated for Table :FCT_CUSTOMER

SELECT BUSINESS_DT, F_F_CUSTOMER_EMPLOYEE_IND, N_F_CUSTOMER_TOT_TXNS, N_F_CUSTOMER_TOT_ATM_TXNS, N_F_CASA_AVG_BAL, V_F_FIC_CUSTOMER_REF_CODE, F_F_CUSTOMER_DORM_PRIM_HLD, F_F_CUSTOMER_IVR_CHN_DORM_PRIM_HLD, F_F_CUSTOMER_ATM_CHN_DORM_PRIM_HLD, F_F_CUSTOMER_POS_CHN_DORM_PRIM_HLD, F_F_CUSTOMER_BRN_CHN_DORM_PRIM_HLD, F_F_CUSTOMER_CLOSED_IND FROM FCT_CUSTOMER ;


-- SQL query generated for Table :FCT_IVR_REGISTRATION

SELECT BUSINESS_DT, V_F_IVR_REG_SRC_CUST_REF_CODE, D_F_IVR_REG_REG_DATE FROM FCT_IVR_REGISTRATION ;


-- SQL query generated for Table :FCT_VP_ATH6

SELECT BUSINESS_DT, V_F_ATH6_CARD_NBR, F_F_ATH6_ECOMM_IND, F_F_ATH6_AUTH_SYS_ACTION FROM FCT_VP_ATH6 ;


-- SQL query generated for Table :INT_FCT_ATM_TXN_DLY

SELECT V_F_ATM_TXN_TYPE, V_F_ATM_TXN_SRC_CUSTOMER_REF_CODE, V_F_ATM_TXN_RESPONDER_CODE, V_F_ATM_TXN_RESP_CODE, V_F_ATM_SRC_TRANSACT_CTRY, BUSINES_DT FROM INT_FCT_ATM_TXN_DLY ;


-- SQL query generated for Table :FCT_DB_ACCOUNTS_REP

SELECT V_F_DB_ACCT_COMB_ACCT_NBR, V_F_DB_ACCT_DIVIDEND_ACCT_NBR, V_F_DB_ACCT_DEBIT_ACCOUNT FROM FCT_DB_ACCOUNTS_REP ;


-- SQL query generated for Table :INT_DB_ACCOUNTS

SELECT BUSINESS_DT, V_F_DB_ACCT_COMB_ACCT_NBR, V_F_DB_ACCT_DIVIDEND_ACCT_NBR, D_F_DB_ACCT_START_DATE, D_F_DB_ACCT_CLOSED_DATE FROM INT_DB_ACCOUNTS ;


-- SQL query generated for Table :INT_FN_ACCOUNT_MASTER

SELECT BUSINESS_DT, N_F_FN_ACCT_REM_TENOR_DAYS, V_F_FN_ACCT_ACCOUNT_NBR, V_F_FN_ACCT_CUSTOMER_REF_CODE, N_F_FN_ACCT_LPP_BILLED_YTD, N_F_FN_ACCT_NET_DISBURSAL_AMT, N_F_FN_ACCT_NPA_STAGE, D_F_FN_ACCT_MIS_DATE FROM INT_FN_ACCOUNT_MASTER ;


-- SQL query generated for Table :INT_NCB_CUSTOMER

SELECT D_F_FW_CUSTOMER_CLOSED_DATE, D_F_FW_CUSTOMER_DATE_ESTB, D_F_FW_CUSTOMER_DOB, F_F_FW_CUSTOMER_GENDER, V_F_FW_CUSTOMER_REF_CODE, V_F_FW_CUSTOMER_SOURCE_SYSTEM, BUSINESS_DT FROM INT_NCB_CUSTOMER ;


-- SQL query generated for Table :INT_TD_ACCOUNTS

SELECT D_F_FWTD_CLOSED_DATE, N_F_FWTD_ORIGINAL_SIZE, V_F_FWTD_CONTRACT_CODE, BUSINESS_DT FROM INT_TD_ACCOUNTS ;


-- SQL query generated for Table :FCT_CAR_FW_BA_BRN_LOCKER_ALLOTMENT

SELECT V_F_FW_COD_ACCT_NO, D_F_FW_DAT_ALLOTMENT FROM FCT_CAR_FW_BA_BRN_LOCKER_ALLOTMENT ;


-- SQL query generated for Table :INT_FCT_BRANCH_TXN_DLY

SELECT N_F_BRANCH_TXN_ACCT_NO, V_F_BRANCH_TXN_TYPE, N_F_BRANCH_TXN_AMT_LCY, F_F_BRANCH_TXN_DRCR_IND, V_F_BRANCH_SRC_CUSTOMER_REF_CODE, D_F_BRANCH_TXN_DATE, V_F_BRANCH_SOURCE_SYSTEM, D_F_BRANCH_POST_DATE, V_F_TXN_TXN_DES FROM INT_FCT_BRANCH_TXN_DLY ;


-- SQL query generated for Table :DIM_VP_MCC_CODE_MASTER

SELECT V_D_VP_MCC_CD_CODE, V_D_VP_MCC_CAT_DESCR FROM DIM_VP_MCC_CODE_MASTER ;


-- SQL query generated for Table :FCT_TXN_CHANNEL

SELECT BUSINESS_DT FROM FCT_TXN_CHANNEL ;


-- SQL query generated for Table :RPT_CUST_PROFITABILITY

SELECT N_D_PROF_AMT_MONTH1, V_D_CUST_BAND, V_F_FIC_CUST_REF_CODE, BUSINESS_DT FROM RPT_CUST_PROFITABILITY ;


-- SQL query generated for Table :FCT_ALL_RELATIONSHIPS

SELECT V_F_ALL_REL_ACCOUNT_NO, V_F_ALL_REL_SAS_CUST_REF_CODE, V_F_ALL_REL_SRC_CUST_REF_CODE, V_F_REL_SOURCE_SYSTEM, BUSINESS_DT, D_F_ALL_REL_ACCT_OPEN_DATE, D_F_ALL_REL_ACCT_CLOSED_DATE FROM FCT_ALL_RELATIONSHIPS ;


-- SQL query generated for Table :RPT_SAL_CUSTOMER_DTLS

SELECT BUSINESS_DT, V_F_SR_CUSTOMER_SAS_CUSTOMER_REF_CODE, V_F_SR_CUSTOMER_REF_CODE, V_F_SR_CUSTOMER_COMP_CODE, V_F_SR_CUSTOMER_NAT_OF_BIZ FROM RPT_SAL_CUSTOMER_DTLS ;


-- SQL query generated for Table :AST_APP_CUST_DETAILS

SELECT MONTHLY_INCOME, DISB_AMT, PROD_TYPE, PROD_CODE, MAT_DAT, DISB_DAT, UCIC_ID, LOAN_NO FROM AST_APP_CUST_DETAILS ;


-- SQL query generated for Table :ARR_MST_FILTER_CITY

SELECT TOP14_TAG, FILTER_CITY, UCIC_ID FROM ARR_MST_FILTER_CITY ;


-- SQL query generated for Table :LIA_MST_NETSAFE_REGN

SELECT REG_DAT, DW_CUST_ID, UCIC_ID FROM LIA_MST_NETSAFE_REGN ;


-- SQL query generated for Table :LIA_MST_HNW

SELECT UCIC_ID, HNW_TYPE, SUB_CAT, CATEGORY, GROUP_ID FROM LIA_MST_HNW ;


-- SQL query generated for Table :VISA_MONEY_TRANSFER

SELECT DAT_POST, FW_CUST_ID FROM VISA_MONEY_TRANSFER ;


